#!/usr/bin/env bash
# Build docs/freshness.md - per-page "last verified" ledger.
#
# Reads `last-updated:` from YAML frontmatter of:
#   - exams/<provider>/<cert>/fact-sheet.md       (cert ledger)
#   - learn/concepts/*.md                          (concept ledger)
#   - learn/*.md                                   (top-level learn pages)
#   - resources/hands-on-projects/*.md             (hands-on ledger)
#
# Pages with no frontmatter show as "unknown". Aim to re-verify every 180 days.
#
# Run locally: bash .github/scripts/build-freshness-ledger.sh > docs/freshness.md

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT" || exit 1

today=$(date -u +%Y-%m-%d)

extract_date() {
    head -20 "$1" | grep -oE '^last-updated:[[:space:]]*[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1 | awk '{print $2}'
}

# Render a sorted markdown table.
# Args: header_label, then files. Display name is the basename without .md.
render_table() {
    local label="$1"; shift
    echo "| $label | Last verified | Path |"
    echo "|--------|---------------|------|"
    local rows=()
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        local name="${f##*/}"; name="${name%.md}"
        [[ "$name" == "README" ]] && continue
        local d
        d=$(extract_date "$f")
        if [[ -z "$d" ]]; then
            rows+=("0000-00-00|$name|unknown|$f")
        else
            rows+=("$d|$name|$d|$f")
        fi
    done
    if [[ ${#rows[@]} -eq 0 ]]; then
        echo "| _(no pages found)_ | | |"
        return
    fi
    printf '%s\n' "${rows[@]}" | sort | while IFS='|' read -r _ name verified path; do
        # Link targets are prefixed with ../ because this ledger renders at docs/freshness.md,
        # while $path is relative to the repo root.
        echo "| $name | $verified | [$path](../$path) |"
    done
}

echo "# Freshness ledger"
echo ""
echo "_Auto-generated by \`.github/scripts/build-freshness-ledger.sh\`. Last build: $today._"
echo ""
echo "Each row shows when a page was last verified against its source of truth."
echo "\"unknown\" means no \`last-updated\` frontmatter yet. Aim to re-verify every 180 days."
echo ""

# --- Certifications ---
echo "## Certifications"
echo ""
echo "| Cert | Last verified | Path |"
echo "|------|---------------|------|"
# Discover certs by fact-sheet.md, not by a notes/ subdir: certs whose notes are still
# outlined but undrafted must appear in the ledger too.
mapfile -t cert_dirs < <(find exams -type f -name fact-sheet.md | sed 's|/fact-sheet.md$||' | sort)
rows=()
for dir in "${cert_dirs[@]}"; do
    fact_sheet="$dir/fact-sheet.md"
    cert_name="${dir#exams/}"
    if [[ ! -f "$fact_sheet" ]]; then
        rows+=("9999-99-99|$cert_name|missing fact-sheet|$dir")
        continue
    fi
    last_updated=$(extract_date "$fact_sheet")
    if [[ -z "$last_updated" ]]; then
        rows+=("0000-00-00|$cert_name|unknown|$dir")
    else
        rows+=("$last_updated|$cert_name|$last_updated|$dir")
    fi
done
printf '%s\n' "${rows[@]}" | sort | while IFS='|' read -r _ name verified path; do
    echo "| $name | $verified | [$path](../$path/) |"
done
echo ""

# --- Concept pages ---
echo "## Concept pages"
echo ""
render_table "Concept" learn/concepts/*.md
echo ""

# --- Hands-on projects ---
echo "## Hands-on projects"
echo ""
render_table "Project" resources/hands-on-projects/*.md
echo ""

# --- Top-level learn pages ---
echo "## Top-level learn pages"
echo ""
render_table "Page" learn/*.md
